=== cceh/sarazenen-wiki/files/sarazenen_masterfassung.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Sarazenen (Personen,Orte,Dokumente+)>

<!ELEMENT Personen (Person)+>

<!ELEMENT Orte (Ort)+>

<!ELEMENT Dokumente (WerkId,WerkTitel,Alternativtitel,Autoren,
                     LebensdatenVerfasser,Abfassungszeitraum,Abfassungsort+,Regionen,Berichtszeitraum,
                     Editionshinweise,EditionLink+,Werkinformation,
                     Quellen)>

<!ELEMENT Person (Id,Name,Rolle+,Alternativnamen?)>

<!ELEMENT WerkId (#PCDATA)>

<!ELEMENT WerkTitel (#PCDATA)>

<!ELEMENT Alternativtitel (Titel)*>

<!ELEMENT Autoren (Autor)+>

<!ELEMENT LebensdatenVerfasser (#PCDATA)>

<!ELEMENT Abfassungsort (#PCDATA)>

<!ELEMENT Regionen (Region)+>

<!ELEMENT Editionshinweise (#PCDATA)>

<!ELEMENT EditionLink (#PCDATA)>
<!ATTLIST EditionLink
  url CDATA #REQUIRED>

<!ELEMENT Werkinformation (#PCDATA)>

<!ELEMENT Quellen (Quelle)*>

<!ELEMENT Rolle (#PCDATA)>

<!ELEMENT Titel (#PCDATA)>

<!ELEMENT Autor (#PCDATA)>
<!ATTLIST Autor
  alt CDATA #IMPLIED>

<!ELEMENT Region (#PCDATA)>

<!ELEMENT Quelle (QuellenId,Zitation,ZeitangabeQuelle,Inhaltsangabe,
                  VolltextOriginalsprache,VolltextUebersetzung,
                  ZitationUebersetzung,ZeitangabeWissenschaft,
                  Berichtszeitraum,Abfassungszeitraum,
                  GeographischesStichwort,Beteiligte,Interaktion,
                  Auffaelligkeiten,Suchbegriffe,Anmerkungen,
                  Entitaeten?)>

<!ELEMENT QuellenId (#PCDATA)>

<!ELEMENT Zitation (#PCDATA)>

<!ELEMENT ZeitangabeQuelle (#PCDATA)>

<!ELEMENT Inhaltsangabe (#PCDATA)>

<!ELEMENT VolltextOriginalsprache (#PCDATA)>

<!ELEMENT VolltextUebersetzung (#PCDATA)>

<!ELEMENT ZitationUebersetzung (#PCDATA)>

<!ELEMENT ZeitangabeWissenschaft (Datum)*>

<!ELEMENT GeographischesStichwort (Ort)*>

<!ELEMENT Beteiligte (Beteiligter)+>

<!ELEMENT Interaktion (#PCDATA)>

<!ELEMENT Auffaelligkeiten (Schlagwort)+>

<!ELEMENT Suchbegriffe (Suchwort)+>

<!ELEMENT Anmerkungen (#PCDATA)>

<!ELEMENT Entitaeten (#PCDATA|Entitaet)*>

<!ELEMENT Beteiligter (#PCDATA)>

<!ELEMENT Schlagwort (#PCDATA)>

<!ELEMENT Suchwort (#PCDATA)>

<!ELEMENT Entitaet (Name)>
<!ATTLIST Entitaet
  Id CDATA #REQUIRED
  Type NMTOKEN #REQUIRED>

<!ELEMENT Id (#PCDATA)>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Alternativnamen (Name)*>

<!ELEMENT Ort (#PCDATA|Alternativnamen|Id|Name|Typ|getty_Id)*>

<!ELEMENT Typ (#PCDATA)>

<!ELEMENT getty_Id (#PCDATA)>

<!ELEMENT Berichtszeitraum (Datum)*>

<!ELEMENT Abfassungszeitraum (Datum)*>

<!ELEMENT Datum (#PCDATA)>
<!ATTLIST Datum
  date CDATA #REQUIRED>

=== cceh/sarazenen-wiki/files/test.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Hier bitte strukturelle Änderungen im Dokument festhalten. Alle strukturellen Änderungen haben Auswirkungen auf die Transformationen!
-->

<!DOCTYPE Sarazenen SYSTEM "sarazenen_masterfassung.dtd">

<Sarazenen>
    <VerfasserInnen>               
      <VerfasserIn>
        <Id>47q8uc8o-m82y-0oca-ldn4-gd5k8qeqmmxa</Id>
        <Name>VerfasserIn unbekannt</Name>
        <Alternativnamen/>       
        <Lebensdaten date=""/>
        <gnd_Id/>
        <wikidata_Id/>
        <viaf_Id/>
      </VerfasserIn>
      <VerfasserIn>
        <Id>3c7e0f93-c523-4340-91e0-d06bc5704d73</Id>
        <Name>Abbo von Saint-Germain</Name>
        <Alternativnamen>
          <Name>Abbo Cernuus</Name>
          <Name>Abbo Parisiensis</Name>
        </Alternativnamen>         
        <Lebensdaten date="845-926">Um 850-nach 921</Lebensdaten>
        <gnd_Id>118646427</gnd_Id>
        <wikidata_Id>Q2622892</wikidata_Id>
        <viaf_Id>25395909</viaf_Id>        
      </VerfasserIn>               
      <VerfasserIn>
        <Id>a2836ba0-dcfd-4638-9bfe-4cb611936525</Id>
        <Name>Abt Hairulf von Oudenbourg</Name>
        <Alternativnamen/>         
        <Lebensdaten date="1050-1199">11./12. Jahrhundert</Lebensdaten>
        <gnd_Id>1089614179</gnd_Id>
        <wikidata_Id>Q3127452</wikidata_Id>
        <viaf_Id>37069954</viaf_Id>        
      </VerfasserIn>               
      <VerfasserIn>
        <Id>fe3467d7-ee66-49fd-a048-7b8e7eda6b05</Id>
        <Name>Adam von Bremen</Name>
        <Alternativnamen>
          <Name>Adam Bremensis</Name>
        </Alternativnamen>         
        <Lebensdaten date="1000-1081">gestorben nach 12.10.1081</Lebensdaten>
        <gnd_Id>11850052X</gnd_Id>
        <wikidata_Id>Q109244</wikidata_Id>
        <viaf_Id>84951025</viaf_Id>        
      </VerfasserIn>                            
    </VerfasserInnen>
    <Personen>
      <Person>
        <Id>bb6d5bfc-33b8-45dc-8054-fd5ea3b76ed9</Id>
        <Name>Vinzenz</Name>
        <Rolle>Heiliger</Rolle>
        <Alternativnamen>
          <Name>Vinzenz von Saragossa</Name>
          <Name>Vinzenz von Valencia</Name>
          <Name>Vicente de Huesca</Name>
        </Alternativnamen>
        <gnd_Id>118937065</gnd_Id>
        <wikidata_Id></wikidata_Id>
        <viaf_Id></viaf_Id>
      </Person>
      <Person>
        <Id>1975d1e5-746e-45cc-8dff-060249603f68</Id>
        <Name>Basiliscus</Name>
        <Rolle>Gesandter König Alfons II. von Galizien und Asturien</Rolle>
        <gnd_Id/>
        <wikidata_Id/>
        <viaf_Id/>
      </Person>
      <Person>
        <Id>22bc55da-c929-4d11-8890-1f0762f6fc41</Id>
        <Name>Froia</Name>
        <Rolle>Gesandter König Alfons II. von Galizien und Asturien</Rolle>
        <gnd_Id/>
        <wikidata_Id/>
        <viaf_Id/>
      </Person>
      <Person>
        <Id>a5c744fe-bff1-444d-8d82-71102d1ba154</Id>
        <Name>Erchenbald</Name>
        <Rolle>Notar</Rolle>
        <Alternativnamen>
          <Name>Herchenbaldus</Name>
          <Name>Erchenbaldus</Name>
          <Name>Erchembaldus</Name>
        </Alternativnamen>
        <gnd_Id/>
        <wikidata_Id/>
        <viaf_Id/>
      </Person>
      <Person>
        <Id>cf8371e9-f27f-44c0-957e-912f3a97dfbf</Id>
        <Name>al-Muzar</Name>
        <Rolle>arabischer Heerführer</Rolle>
        <Alternativnamen>
          <Name>Almuzar</Name>
        </Alternativnamen>
        <gnd_Id/>
        <wikidata_Id/>
        <viaf_Id/>
      </Person>
      <Person>
        <Id>c8660913-da05-439f-9ded-1583aae8283c</Id>
        <Name>Muawiya ibn Abi Sufyan</Name>
        <Rolle>Kalif von Damaskus</Rolle>
        <Alternativnamen>
          <Name>Moabia</Name>
          <Name>Mu’awiya ibn Abi Sufyan</Name>
        </Alternativnamen>
        <gnd_Id>119217481</gnd_Id>
        <wikidata_Id>Q181154</wikidata_Id>
        <viaf_Id>39541902</viaf_Id>
      </Person>
    </Personen>
    <Orte>
        <Ort>
            <Id>8e99e0e8-9706-41eb-ae38-9e2162d07913</Id>
            <Name>Tripolis (Libanon)</Name>
            <Typ>Ort</Typ>
            <Alternativnamen>
                <Name>Tripolim</Name>
                <Name>Tripoleos</Name>
                <Name>Tripoli</Name>
                <Name>Tripolis (Libanon)</Name>
            </Alternativnamen>
          <getty_Id>7002314</getty_Id>
        </Ort>
        <Ort>
            <Id>7f5ce30a-4607-4cce-9f6d-d38ee6c9c3e1</Id>
            <Name>Cádiz</Name>
            <Typ>Ort</Typ>
            <Alternativnamen>
                <Name>Cadiz</Name>
                <Name>Gaditanum</Name>
            </Alternativnamen>
          <getty_Id>7008799</getty_Id>
        </Ort>
        <Ort>
            <Id>00070550-190f-431b-84b4-9c6591b1c146</Id>
            <Name>Gibraltar</Name>
            <Typ>Region</Typ>
            <Alternativnamen>
                <Name>columnas Herculis</Name>
            </Alternativnamen>
            <getty_Id>7005233</getty_Id>
        </Ort>
        <Ort>
            <Id>c477d5d1-80e9-4857-86ee-adb01c77a947</Id>
            <Name>Algeciras</Name>
            <Typ>Ort</Typ>
            <Alternativnamen>
                <Name>Mesulam</Name>
            </Alternativnamen>
            <getty_Id>7007258</getty_Id>
        </Ort>
        <Ort>
            <Id>a4c3cf7d-8abf-4bcb-8c30-037fc2d02da5</Id>
            <Name>Orbieu</Name>
            <Typ>Fluss</Typ>
            <Alternativnamen>
                <Name>Oliveio</Name>
            </Alternativnamen>
            <getty_Id>1128136</getty_Id>
        </Ort>
    </Orte>
      <Dokumente>
    <WerkId>0001</WerkId>
    <WerkTitel>Chronicon sive Gesta Saxonum</WerkTitel>
    <Alternativtitel>
      <Titel>Chronik</Titel>
      <Titel>Geschichte der Sachsen</Titel>
    </Alternativtitel>
    <Autoren>
      <Autor Id="y5a6neek-hz0i-fke2-hzhk-yve3rwp0fc9r">Thietmar von Merseburg</Autor>
    </Autoren>
    <LebensdatenVerfasserIn>975-1018</LebensdatenVerfasserIn>
    <Abfassungszeitraum>
      <Datum date="1012-1018">1012-1018</Datum>
    </Abfassungszeitraum>
    <Abfassungsort>Merseburg</Abfassungsort>
    <Regionen>
      <Region>West- und Mitteleuropa – Ostfrankenreich</Region>
    </Regionen>
    <Berichtszeitraum>
      <Datum date="901-1018">901-1018</Datum>
    </Berichtszeitraum>
    <Editionshinweise>Thietmar von Merseburg, Chronicon, ed. Robert Holtzmann (MGH SS rer. Germ. N.S. 9), Berlin 1935.</Editionshinweise>
    <EditionLink url="https://www.dmgh.de/de/fs1/object/display/bsb00000689_meta:titlePage.html?sortIndex=010:060:0009:010:00:00">Digitalisat bei dMGH.de</EditionLink>
    <Werkinformation>Das Chronicon sive Gesta Saxonum, auch Chronik oder Geschichte der Sachsen genannt, wurde von Thietmar von Merseburg zwischen 1012 und 1018 in acht Büchern verfasst. Thietmar, seit 1009 Bischof von Merseburg, berichtet seit Beginn des zehnten Jahrhunderts bis zu seinem Tod über die Geschichte seines Bistums.
Vgl. auch mit Hinweisen für weiterführende Literatur Thietmarus ep. Merseburgensis, Chronicon sive Gesta Saxonum, in: Repertorium ‚Geschichtsquellen des deutschen Mittelalters‘ [http://www.geschichtsquellen.de/repOpus_04425.html 2016-08-01]; Gerd Althoff, Art. Thietmar v. Merseburg, in: Lexikon des Mittelalters 8, Sp. 694-695 [Brepolis Medieval Encyclopaedias – Lexikon des Mittelalters Online, 2016-08-01]; David A. Warner, Art. Thietmar of Merseburg, in: Encyclopedia of the Medieval Chronicle 2 (2010), S. 1424f.</Werkinformation>
    <gnd_Id>4668392-6</gnd_Id>
    <wikidata_Id/>
    <viaf_Id>278615725</viaf_Id>
    <Quellen>
      <Quelle>
        <QuellenId>0001</QuellenId>
        <Zitation>Thietmar, Chronicon II, 25, ed. Holtzmann 1935, S. 68-71.</Zitation>
        <ZeitangabeQuelle>970</ZeitangabeQuelle>
        <Inhaltsangabe>Kurz bevor Sarazenen die Stadt Jerusalem einnehmen, stirbt Hidda, die Mutter von Erzbischof Gero von Köln, um 970 [965/69] während einer Pilgerfahrt.</Inhaltsangabe>
        <VolltextOriginalsprache>Huius [Ebf. Gero von Köln] sancta mater, Hidda nomine, Ierusalem [Jerusalem] orationis gratia petens infirmata, hanc suis legationem pedissequis commendavit: ‘Egredienti animae meimet prolongato huius exilii incolatu, corpus meum matri terre celeriter tradite et, mox euntes, haec filio nunciate Geroni, quo peregrinae genitrici suae talem in terris non deneget honorem, qualem pius in caelis dare dignatus est Deus, et altare mihi in aecclesia sanctae constituat Ceciliae.’ Talibus preceptis devotae obtemperantes famule dominam suam post haec feliciter exspirantem sepelierunt et statim recendetes miseriam insciae effugierunt subsecuturam. Nam Saraceni Ierusolimam tunc invadentes nil reliquere vicits, quod sancta eis clam tunc predixit matrona, cum se mortuam iussit propere tumulari et suas abire.</VolltextOriginalsprache>
        <VolltextUebersetzung>Seine [Ebf. Gero von Köln] fromme Mutter Hidda war nach Jerusalem [Jerusalem] gezogen um zu beten, und dort erkrankt. Da trug sie ihren Begleiterinnen folgende Botschaft auf: „Wenn meine Seele den Wohnort ihres langen Pilgerlebens verläßt, übergibt meinen Leib schnell der Mutter Erde und brecht sofort mit der Nachricht zu meinem Sohne Gero auf, damit er der fernen Mutter auf Erden nicht die Ehren verweigere, deren mich der gütige Gott im Himmel gewürdigt hat; in der Kirche der hl. Cäcilie soll er mir einen Altar errichten.“ Diesen Anweisungen gehorsam begruben dann ihre ergebenen Dienerinnen die selig verschiedene Herrin, kehrten sogleich heim und entrannen dadurch, ohne es zu ahnen, nahendem Unheil. Denn damals eroberten die Sarazenen Jerusalem und ließen den Besiegten nichts; das aber hatte ihnen die heilige Frau damals verhüllt vorausgesagt, als sie befahl, sie nach ihrem Tode sofort zu bestatten und dann abzureisen.</VolltextUebersetzung>
